In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df_vendas = pd.read_excel(r"C:\Users\igor_\OneDrive\Desktop\FACULDADE\vendas.xlsx",) # Lendo o arquivo Excel e armazenando em um DataFrame chamado df_vendas
display(df_vendas)

,id_venda,data_venda,id_cliente,idade_cliente,cidade,categoria_produto,quantidade,valor_unitario,valor_total
0,V00118,2025-03-27,C0026,40.0,Salvador,Esporte,1,501.61,501.61
1,V00513,2025-10-20,C0089,39.0,Rio de Janeiro,Beleza,2,105.69,211.38
2,V00398,2025-08-13,C0009,20.0,São Paulo,Casa e Cozinha,3,326.75,980.25
3,V00530,2025-07-11,C0027,56.0,Porto Alegre,Eletrônicos,4,3498.05,13992.2
4,V00437,2025-06-21,C0069,34.0,Natal,Esporte,3,109.1,327.3
...,...,...,...,...,...,...,...,...,...
595,V00391,2025-04-10,C0014,63.0,João Pessoa,Beleza,1,334.01,334.01
596,V00026,2025-08-24,C0098,50.0,Aracaju,Beleza,1,303.05,303.05
597,V00110,2025-07-16,C0083,-3.0,Maceió,Beleza,1,343.62,343.62
598,V00536,2025-09-01,C0088,67.0,João Pessoa,Esporte,1,178.98,178.98
599,V00014,2025-12-27,C0063,59.0,Fortaleza,Casa e Cozinha,3,158.82,476.46

In [2]:
df_vendas.shape # utilizei o shape para verificar a quantidade de linhas e colunas do dataframe

(600, 9)

In [3]:
df_vendas.dtypes #tipo de dados de cada coluna do dataframe

id_venda                        str
data_venda           datetime64[us]
id_cliente                      str
idade_cliente               float64
cidade                          str
categoria_produto               str
quantidade                    int64
valor_unitario               object
valor_total                  object
dtype: object

In [4]:
df_vendas.head() # Mostrando apenas as 5 primeiras linhas do dataframe

,id_venda,data_venda,id_cliente,idade_cliente,cidade,categoria_produto,quantidade,valor_unitario,valor_total
0,V00118,2025-03-27,C0026,40.0,Salvador,Esporte,1,501.61,501.61
1,V00513,2025-10-20,C0089,39.0,Rio de Janeiro,Beleza,2,105.69,211.38
2,V00398,2025-08-13,C0009,20.0,São Paulo,Casa e Cozinha,3,326.75,980.25
3,V00530,2025-07-11,C0027,56.0,Porto Alegre,Eletrônicos,4,3498.05,13992.2
4,V00437,2025-06-21,C0069,34.0,Natal,Esporte,3,109.1,327.3

In [5]:
df_vendas = df_vendas.rename(columns={'id_venda': 'ID Venda', 'data_venda': 'Data Venda', 'id_cliente': 'ID Cliente', 'idade_cliente':'Idade Cliente', 'categoria_produto':'Categoria Produto' ,'valor_unitario': 'Valor Unitario', 'valor_total':'Valor Total'})
display(df_vendas) # Mostrando o dataframe após a renomeação das colunas

,ID Venda,Data Venda,ID Cliente,Idade Cliente,cidade,Categoria Produto,quantidade,Valor Unitario,Valor Total
0,V00118,2025-03-27,C0026,40.0,Salvador,Esporte,1,501.61,501.61
1,V00513,2025-10-20,C0089,39.0,Rio de Janeiro,Beleza,2,105.69,211.38
2,V00398,2025-08-13,C0009,20.0,São Paulo,Casa e Cozinha,3,326.75,980.25
3,V00530,2025-07-11,C0027,56.0,Porto Alegre,Eletrônicos,4,3498.05,13992.2
4,V00437,2025-06-21,C0069,34.0,Natal,Esporte,3,109.1,327.3
...,...,...,...,...,...,...,...,...,...
595,V00391,2025-04-10,C0014,63.0,João Pessoa,Beleza,1,334.01,334.01
596,V00026,2025-08-24,C0098,50.0,Aracaju,Beleza,1,303.05,303.05
597,V00110,2025-07-16,C0083,-3.0,Maceió,Beleza,1,343.62,343.62
598,V00536,2025-09-01,C0088,67.0,João Pessoa,Esporte,1,178.98,178.98
599,V00014,2025-12-27,C0063,59.0,Fortaleza,Casa e Cozinha,3,158.82,476.46

In [6]:
df_vendas.info() # Mostrando informações sobre o dataframe, como quantidade de linhas, colunas e tipos de dados

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID Venda           600 non-null    str
 1   Data Venda         600 non-null    datetime64[us]
 2   ID Cliente         600 non-null    str
 3   Idade Cliente      581 non-null    float64
 4   cidade             586 non-null    str
 5   Categoria Produto  600 non-null    str
 6   quantidade         600 non-null    int64
 7   Valor Unitario     600 non-null    object
 8   Valor Total        600 non-null    object
dtypes: datetime64[us](1), float64(1), int64(1), object(2), str(4)
memory usage: 42.3+ KB

In [7]:
# 1. Total de valores ausentes em todas as colunas da base
print("=== VALORES AUSENTES POR COLUNA ===")
print(df_vendas.isnull().sum())

# 2. Total de registros duplicados na base inteira
print("\n=== REGISTROS DUPLICADOS ===")
print(f"Total de linhas duplicadas: {df_vendas.duplicated().sum()}")

=== VALORES AUSENTES POR COLUNA ===
ID Venda              0
Data Venda            0
ID Cliente            0
Idade Cliente        19
cidade               14
Categoria Produto     0
quantidade            0
Valor Unitario        0
Valor Total           0
dtype: int64

=== REGISTROS DUPLICADOS ===
Total de linhas duplicadas: 20

In [8]:
df_vendas["Valor Total"].describe() # Mostrando estatísticas descritivas do dataframe, como média, desvio padrão, valores mínimos e máximos, entre outros.

count     600
unique    579
top       476
freq        2
Name: Valor Total, dtype: int64

In [9]:
df_vendas.duplicated(subset=['ID Venda']).sum() # Verificando se há valores duplicados no dataframe

print(df_vendas['ID Venda'].value_counts().head(10)) # Mostra os 10 IDs de vendas que mais se repetem na base

id_teste = "V00556"
display(df_vendas[df_vendas['ID Venda'] == id_teste]) #Verificando se o ID de venda "V00556" está presente no dataframe e mostrando as linhas correspondentes a esse ID.


df_vendas_limpo =df_vendas.drop_duplicates(subset=['ID Venda'], keep='first') # Removendo valores duplicados do dataframe, mantendo apenas a primeira ocorrência de cada ID de venda.

print("Duplicatas restantes:", df_vendas_limpo.duplicated(subset=['ID Venda']).sum()) #rodando novamente a verificação de valores duplicados no dataframe após a remoção das duplicatas.

ID Venda
V00556    2
V00331    2
V00119    2
V00293    2
V00136    2
V00206    2
V00215    2
V00428    2
V00433    2
V00354    2
Name: count, dtype: int64

,ID Venda,Data Venda,ID Cliente,Idade Cliente,cidade,Categoria Produto,quantidade,Valor Unitario,Valor Total
6,V00556,2025-03-05,C0006,61.0,Natal,Eletrônicos,1,476,476
452,V00556,2025-03-05,C0006,61.0,Natal,Eletrônicos,1,476,476

Duplicatas restantes: 0

In [14]:
print(df_vendas.isnull().any()) # Verificando se há valores nulos no dataframe

# Mostra a quantidade de nulos e a porcentagem que eles representam nas duas colunas
nulos_idade = df_vendas_limpo['Idade Cliente'].isnull().sum()
nulos_cidade = df_vendas_limpo['cidade'].isnull().sum()
total_linhas = len(df_vendas_limpo)

print(f"Idades faltando: {nulos_idade} ({nulos_idade / total_linhas * 100:.2f}%)")
print(f"Cidades faltando: {nulos_cidade} ({nulos_cidade / total_linhas * 100:.2f}%)")

ID Venda             False
Data Venda           False
ID Cliente           False
Idade Cliente        False
cidade               False
Categoria Produto    False
quantidade           False
Valor Unitario       False
Valor Total          False
dtype: bool
Idades faltando: 18 (3.10%)
Cidades faltando: 14 (2.41%)

In [13]:
df_vendas['cidade']=df_vendas['cidade'].fillna('Não Informado') # Preenchendo valores nulos na coluna cidade com "Não Informado"

mediana_idade = df_vendas['Idade Cliente'].median() # Calculando a mediana da coluna idade_cliente
df_vendas['Idade Cliente'] = df_vendas['Idade Cliente'].fillna(mediana_idade)



# Verifica se ainda sobrou algum NaN nas colunas cidade e Idade Cliente
print(df_vendas[['cidade', 'Idade Cliente']].isnull().sum())# Preenchendo valores nulos na coluna idade_cliente com a mediana calculada

cidade           0
Idade Cliente    0
dtype: int64

In [15]:
colunas_financeiras = ['Valor Unitario', 'Valor Total']

for coluna in colunas_financeiras:
  # Converte diretamente para numérico. Se houver algum texto inválido, vira NaN de forma segura.
  df_vendas[coluna] = pd.to_numeric(df_vendas[coluna], errors='coerce')

# Confere os tipos e se sobrou algum valor nulo
print(df_vendas[['Valor Unitario', 'Valor Total']].dtypes)
print(df_vendas[['Valor Unitario', 'Valor Total']].isnull().sum())

Valor Unitario    float64
Valor Total       float64
dtype: object
Valor Unitario    15
Valor Total       18
dtype: int64

In [18]:
# 1. Total de valores ausentes em todas as colunas da base
print(df_vendas.isnull().sum())

# 2. Total de registros duplicados na base inteira
print(f"Total de linhas duplicadas: {df_vendas.duplicated().sum()}")

ID Venda             0
Data Venda           0
ID Cliente           0
Idade Cliente        0
cidade               0
Categoria Produto    0
quantidade           0
Valor Unitario       0
Valor Total          0
dtype: int64
Total de linhas duplicadas: 20

In [19]:
condicao_vt = (
    df_vendas['Valor Total'].isnull() #mostrando a condição para calcular o valor total quando ele estiver faltando, mas temos o valor unitário e a quantidade
    & df_vendas['Valor Unitario'].notnull() #mostrando a condição para calcular o valor total quando ele estiver faltando, mas temos o valor unitário e a quantidade
    & df_vendas['quantidade'].notnull() #mostrando a condição para calcular o valor total quando ele estiver faltando, mas temos o valor unitário e a quantidade
)
df_vendas.loc[condicao_vt, 'Valor Total'] = (
    df_vendas.loc[condicao_vt, 'Valor Unitario'] #utilizando a função loc para localizar as linhas que atendem à condição e calcular o valor total multiplicando o valor unitário pela quantidade   
    * df_vendas.loc[condicao_vt, 'quantidade']
)

# 2. Se o 'Valor Unitario' está faltando, mas temos 'Valor Total' e 'Quantidade'
condicao_vu = (
    df_vendas['Valor Unitario'].isnull() #mostrando a condição para calcular o valor unitário quando ele estiver faltando, mas temos o valor total e a quantidade
    & df_vendas['Valor Total'].notnull() #mostrando a condição para calcular o valor unitário quando ele estiver faltando, mas temos o valor total e a quantidade
    & df_vendas['quantidade'].notnull() #mostrando a condição para calcular o valor unitário quando ele estiver faltando, mas temos o valor total e a quantidade
    & (df_vendas['quantidade'] > 0)
)
df_vendas.loc[condicao_vu, 'Valor Unitario'] = (
    df_vendas.loc[condicao_vu, 'Valor Total']
    / df_vendas.loc[condicao_vu, 'quantidade']  # ou .loc[condicao_vu, 'Quantidade']
)

# 3. Verifique quantos nulos restaram após o recálculo
print(df_vendas[['Valor Unitario', 'Valor Total']].isnull().sum())

df_vendas = df_vendas.dropna(subset=['Valor Unitario', 'Valor Total'])
print(df_vendas[['Valor Unitario', 'Valor Total']].isnull().sum())

Valor Unitario    0
Valor Total       0
dtype: int64
Valor Unitario    0
Valor Total       0
dtype: int64

In [20]:
# Converte toda a coluna de cidade para maiúsculas
df_vendas_limpo['cidade'] = df_vendas_limpo['cidade'].str.upper()
display(df_vendas_limpo) # Mostrando o dataframe após a conversão da coluna cidade para maiúsculas

,ID Venda,Data Venda,ID Cliente,Idade Cliente,cidade,Categoria Produto,quantidade,Valor Unitario,Valor Total
0,V00118,2025-03-27,C0026,40.0,SALVADOR,Esporte,1,501.61,501.61
1,V00513,2025-10-20,C0089,39.0,RIO DE JANEIRO,Beleza,2,105.69,211.38
2,V00398,2025-08-13,C0009,20.0,SÃO PAULO,Casa e Cozinha,3,326.75,980.25
3,V00530,2025-07-11,C0027,56.0,PORTO ALEGRE,Eletrônicos,4,3498.05,13992.2
4,V00437,2025-06-21,C0069,34.0,NATAL,Esporte,3,109.1,327.3
...,...,...,...,...,...,...,...,...,...
595,V00391,2025-04-10,C0014,63.0,JOÃO PESSOA,Beleza,1,334.01,334.01
596,V00026,2025-08-24,C0098,50.0,ARACAJU,Beleza,1,303.05,303.05
597,V00110,2025-07-16,C0083,-3.0,MACEIÓ,Beleza,1,343.62,343.62
598,V00536,2025-09-01,C0088,67.0,JOÃO PESSOA,Esporte,1,178.98,178.98
599,V00014,2025-12-27,C0063,59.0,FORTALEZA,Casa e Cozinha,3,158.82,476.46

PROBLEMAS ENCONTRADOS:REGISTROS DUPLICADOS , PRECISEI FAZER A REMOÇÃO DE DUPLICATAS PARA NAO GERAR VALORES QUE VAO AFETAR A ANALISE, PADRONIZAÇAO DOS CAMPOS DA INFORMAÇAO PARA UMS MELHOR VIZUALIZAÇÃO, TRATAMENTO DE VALORES NULOS APLICANDO NAO INFORMADO PARA TEXTOS E MEDIANA PARA NUMEROS USANDO ESSA ABORDAGEM TRAZ UMA PRECISAO TECNICA DE ANALISE QUANTO PARA PROTEÇÃO QUANTO PARA O RESULTADO DE NEGOCIOS.

"Durante a análise exploratória, identificou-se a presença de valores ausentes nas colunas financeiras: foram constatadas 15 lacunas no coluna Valor Unitario e 18 lacunas na coluna Valor Total. Esses registros precisarão de tratamento (como remoção ou imputação)."

Como os atributos de valor financeiro (Valor Unitario e Valor Total) são críticos para a integridade de qualquer análise de faturamento, optou-se por [remover os 15/18 registros inconsistentes / recalcular os valores faltantes com base na quantidade]. Decidiu-se não utilizar imputação estatística (como média ou mediana) nesses campos para evitar distorções nos indicadores do e-commerce."

Para o tratamento dos valores ausentes identificados nas colunas financeiras, adotou-se uma estratégia baseada em regra de negócio: os campos faltantes foram recalculados matematicamente utilizando a relação entre Valor Unitario, Valor Total e Quantidade. Apenas os registros sobraram que não possuíam informações suficientes para o recálculo foram descartados, garantindo a integridade e a precisão das análises de faturamento subsequentes sem o uso de imputações estatísticas artificiais."

A-- Qual é o valor médio das compras realizadas? 
 média de compras é: 1244.81

Esse indicador é fundamental para:
Previsão de Faturamento: Estimar quantas vendas são necessárias para atingir metas financeiras.Planejamento de Vendas e Marketing: Avaliar se a estratégia comercial está atraindo clientes com maior poder de compra ou se estratégias devem ser aplicadas para aumentar o valor de cada carrinho.

In [ ]:
Media_compras= df_vendas['Valor Total'].mean()
print(f"A média de compras é: {Media_compras:.2f}")

A média de compras é: 1244.81

B-- Qual categoria de produto apresenta o maior valor total de vendas? 
R: ELETRONICOS É A CATEGORIA QUE APRESENTA O MAIOR VALOR TOTAL DE VENDAS

A liderança dos Eletrônicos no faturamento total traz direcionamentos estratégicos relevantes:
Representatividade na Receita: A categoria de Eletrônicos é o principal motor de entrada de caixa do negócio. Por possuírem, em geral, um valor unitário mais elevado (ticket médio alto), poucas vendas dessa categoria já impactam significativamente o faturamento geral.Gestão de Estoque e Cadeia de Suprimentos: Devido ao seu alto peso financeiro, o controle de estoque dessa categoria exige prioridade máxima.Foco Comercial e Parcerias: Reforça a importância de negociar melhores margens e condições de pagamento com fornecedores de tecnologia, além de direcionar campanhas publicitárias para os produtos que mais trazem retorno financeiro.

In [151]:
maior_categoria = df_vendas.groupby('Categoria Produto')['Valor Total'].sum().idxmax()
ranking_categorias = df_vendas.groupby('Categoria Produto')['Valor Total'].sum().reset_index().sort_values(by='Valor Total', ascending=False).head(5)
display(ranking_categorias)

  Categoria Produto  Valor Total
3       Eletrônicos    315927.66
5       Informática    225359.40
2    Casa e Cozinha     74882.28
4           Esporte     46897.36
7              Moda     33763.59

C-- Quais são as três cidades com maior quantidade de vendas registradas? 
R: AS 3 CIDADES COM MAIOR QUANTIDADE DE VENDAS SAO RIO DE JANEIRO CURITIBA E JOAO PESSOA

A presença dessas três capitais no topo do volume de vendas traz desdobramentos operacionais e estratégicos importantes:
Concentração e Presença de Mercado: Indica onde a marca possui maior penetração e apelo comercial. Rio de Janeiro, Curitiba e João Pessoa representam os principais polos geradores de tráfego de clientes e volume de pedidos.Otimização de Logística e Frete: Como o volume de entregas nessas regiões é elevado, a empresa pode buscar acordos comerciais com transportadoras locais ou estruturar centros de distribuição estratégicos para reduzir prazos de entrega e custos com freteAnálise Demográfica e Expansão: Serve de parâmetro para mapear cidades vizinhas ou de perfil socioeconômico semelhante que possam ter potencial de expansão para novas estratégias de captação.

In [152]:
top3_cidades = df_vendas['cidade'].value_counts().head(10)
display(top3_cidades)

cidade
Rio de Janeiro    68
Curitiba          59
João Pessoa       51
Aracaju           43
Natal             42
Porto Alegre      39
Belo Horizonte    39
São Paulo         36
Recife            36
Maceió            36
Name: count, dtype: int64

D-- Qual é a média de idade dos clientes presentes na base após o tratamento dos dados? 


Adequação de Linguagem: Clientes na faixa dos 40 a 50 anos tendem a valorizar processos de compra diretos, seguros e com navegação clara. A comunicação visual das campanhas e a usabilidade do site ou aplicativo devem ser intuitivas e objetivas.Canais de Atendimento e Relacionamento: Esse público costuma priorizar canais de atendimento eficientes, transparentes e com suporte humano ágil quando necessário (como WhatsApp, e-mail e suporte estruturado), em comparação com públicos extremamente jovens que preferem interações 100% automatizadas em redes sociais.
Alinhamento de Mix de Produtos: Auxilia na seleção do portfólio de produtos e serviços adicionais (como garantias estendidas, planos de suporte ou opções de parcelamento facilitadas) que façam sentido para o momento de vida e capacidade financeira dessa faixa etária.

In [146]:
media_idade = df_vendas['Idade Cliente'].mean()
print(f"Média de idade dos clientes: {media_idade:.1f} anos")

Média de idade dos clientes: 46.3 anos

E-- Qual cliente apresentou o maior valor acumulado em compras?
Cliente com maior valor acumulado: C0041 (Total: R$ 32483.78)

O cliente C0041 é um exemplo de ativo de alto valor que exige acompanhamento próximo.Estratégias de Retenção e Relacionamento: Perder um cliente com esse volume de compras teria um impacto direto e imediato na receita. Por isso, ele é candidato prioritário para programas de fidelidade, atendimento personalizado, ofertas exclusivas e canais diretos de pós-venda.Mapeamento de Perfil: Analisar o comportamento de compra, o histórico e as características do C0041 ajuda a criar o perfil do cliente ideal. Essa inteligência permite direcionar esforços de aquisição para atrair novos consumidores com hábitos e orçamento semelhantes.

In [148]:

ranking_clientes = df_vendas.groupby('ID Cliente')['Valor Total'].sum().reset_index().sort_values(by='Valor Total', ascending=False).head(5)
display(ranking_clientes)




cliente_top = df_vendas.groupby('ID Cliente')['Valor Total'].sum().idxmax()
valor_total_cliente = df_vendas.groupby('ID Cliente')['Valor Total'].sum().max()

print(f"Cliente com maior valor acumulado: {cliente_top} (Total: R$ {valor_total_cliente:.2f})")

   ID Cliente  Valor Total
39      C0041     32483.78
95      C0099     22083.41
43      C0045     20148.36
80      C0083     18123.69
25      C0027     16416.07

Cliente com maior valor acumulado: C0041 (Total: R$ 32483.78)